config/routes.rb
Spree::Core::Engine.routes.draw do
  # Add your extension routes here
  namespace :admin do
    resources :banks, :except => [:show, :destroy] do
      put :toggle_activation, :on => :member
    end
  end
end

app/models/spree/bank.rb
module Spree
  class Bank < ActiveRecord::Base
    attr_accessible :name, :account_owner, :account_no, :active
    validates :name, :account_owner, :account_no, :presence => true
    validates_uniqueness_of :account_no , :scope => :name

    scope :active, where(:active => true)
  end
end

app/models/spree/payment_method/bank_transfer.rb
module Spree
  class PaymentMethod::BankTransfer < PaymentMethod
    
    def actions
      %w{capture void}
    end

    # Indicates whether its possible to capture the payment
    def can_capture?(payment)
      ['checkout', 'pending'].include?(payment.state)
    end

    # Indicates whether its possible to void the payment.
    def can_void?(payment)
      payment.state != 'void'
    end

    def capture(*args)      
      begin
        order_number = args[2][:order_id].split('-')[0]
        order = Spree::Order.where(:number => order_number).first
        OrderMailer.confirm_email(order).deliver
      rescue Exception => e
        logger.error("#{e.class.name}: #{e.message}")
        logger.error(e.backtrace * "\n")
      end
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end

    def void(*args)
      ActiveMerchant::Billing::Response.new(true, "", {}, {})
    end

    def source_required?
      false
    end

  end
end

app/controllers/spree/admin/banks_controller.rb
module Spree
  module Admin
    class BanksController < ResourceController
      def index
        @banks = Spree::Bank.page(params[:page])
      end

      def toggle_activation
        @success = @bank.toggle!(:active)
      end
    end
  end
end

app/helpers/spree/admin/banks_helper.rb
module Spree
  module Admin
    module BanksHelper

      def bank_status(bank)
        bank.active? ? 'Activa' : 'Inactiva'
      end

      def action_to_toggle_bank_status(bank) 
        bank.active? ? 'Desactivar' : 'Activar'
      end

    end
  end
end

app/views/spree/admin/banks/_form.html.erb
<%= render :partial => 'spree/shared/error_messages', :locals => { :target => @bank } %>

<%= form_for [:admin, @bank] do |f| %>
  <div data-hook="admin_inside_bank_form" class="row">
    <div class="alpha five columns">      
      <%= f.field_container :name do %>
        <%= f.label :name, t(:name) %> <span class="required">*</span><br />
        <%= f.error_message_on :name, :class => 'fullwidth title' %>
        <%= f.text_field :name, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :account_owner do %>
        <%= f.label :account_owner, t(:account_owner) %> <span class="required">*</span><br />
        <%= f.error_message_on :account_owner, :class => 'fullwidth title' %>
        <%= f.text_field :account_owner, :class => 'fullwidth' %>
      <% end %>

      <%= f.field_container :account_no do %>
        <%= f.label :account_no, t(:account_no) %><span class="required">*</span><br />
        <%= f.text_field :account_no, :class => 'fullwidth' %>
      <% end %>
      
      <%= f.field_container :active do %>
        <%= f.check_box :active %>
        <%= f.label :active, t(:active) %>
      <% end %>

      <%= button t('actions.update'), 'icon-ok' %>
    </div>
  </div>
<% end %>

app/views/spree/admin/banks/edit.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:edit_bank) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:back_to_banks_list), admin_banks_path, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= render :partial => 'form' %>

app/views/spree/admin/banks/index.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:listing_banks) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to "+ " + t(:new_bank), new_admin_bank_path %>
  </li>
<% end %>

<%= paginate @banks %>

<table class='index'>
  <thead>
    <tr>      
      <th><%= t(:name) %></th>
      <th><%= t(:account_owner) %></th>
      <th><%= t(:account_no) %></th>
      <th><%= t(:active) %></th>
    </tr>
  </thead>
  
  <tbody>
    <% @banks.each do |bank| %>
      <tr class="<%= cycle('odd', 'even') %>">        
        <td class="align-center"><%= bank.name %></td>
        <td class="align-center"><%= bank.account_owner %></td>
        <td class="align-center"><%= bank.account_no %></td>
        <td class="align-center" id='active-status-<%= bank.id %>'><%= bank_status(bank) %></td>
        <td class="actions"><%= link_to action_to_toggle_bank_status(bank), toggle_activation_admin_bank_path(bank), :remote => true, :method => :put %></td>
        <td class="actions"><%= link_to_edit bank, :no_text => true, :class => 'edit' %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/spree/admin/banks/new.html.erb
<%= render :partial => 'spree/admin/shared/configuration_menu' %>

<% content_for :page_title do %>
  <%= t(:new_bank) %>
<% end %>

<% content_for :page_actions do %>
  <li>
    <%= button_link_to t(:back_to_banks_list), admin_banks_path, :icon => 'icon-arrow-left' %>
  </li>  
<% end %>

<%= render :partial => 'form' %>    

app/views/spree/admin/banks/toggle_activation.js.erb
<% if @success %>
  $('#active-status-<%= @bank.id %>').text('<%= bank_status(@bank) %>')
  $('a[href="<%= toggle_activation_admin_bank_path(@bank) %>"]').text('<%= action_to_toggle_bank_status(@bank) %>')
<% else %>
  alert('<%= @bank.errors.full_messages.to_sentence %>')
<% end %>

app/views/spree/checkout/payment/_banktransfer.html.erb
<% if (banks = Spree::Bank.active).any? %>
  <p>Para completar el pedido tendrá que realizar una transferencia desde su banco o caja. Una vez hayamos recibido la transferencia procederemos al envio de tu pedido.</p>
  <p>Estos son los datos que deberá proporcionar a su banco o caja para realizar la transferencia. Cuenta<%="s" if banks.size > 1 %>:</p>  
  <div class="datos-banco">  
  <% banks.each do |bank| %>
    <p><strong>Destinatario:</strong> <%= bank.account_owner %></p>
    <p><strong>Entidad:</strong> <%= bank.name %></p>
    <p><strong>Cuenta Bancaria:</strong> <%= bank.account_no %></p>
    <p><strong>Concepto:</strong> <%= @order.number %></p>
    <p><strong>Importe:</strong> <%= @order.display_total %></p>
  <% end %>  
  </div>
<% end %>